# Area Labels
'area/web':
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

'area/admin':
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

'area/api':
  - changed-files:
      - any-glob-to-any-file: 'packages/api/**/*'

'area/ui':
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

'area/db':
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

# Type Labels
'type/feat':
  - head-branch: ['feat/*', 'feature/*']

'type/fix':
  - head-branch: ['fix/*', 'hotfix/*']

'type/chore':
  - head-branch: ['chore/*']

'type/docs':
  - head-branch: ['docs/*']

'type/test':
  - head-branch: ['test/*']

'type/refactor':
  - head-branch: ['refactor/*']

'type/ci':
  - head-branch: ['ci/*']
