"area: web":
  - changed-files:
    - any-glob-to-any-file: 'apps/web/**/*'

"area: admin":
  - changed-files:
    - any-glob-to-any-file: 'apps/admin/**/*'

"area: droid":
  - changed-files:
    - any-glob-to-any-file: 'apps/droid/**/*'

"area: database":
  - changed-files:
    - any-glob-to-any-file: 'packages/database/**/*'

"area: ui":
  - changed-files:
    - any-glob-to-any-file: 'packages/ui/**/*'

"area: utils":
  - changed-files:
    - any-glob-to-any-file: 'packages/utils/**/*'

"config":
  - changed-files:
    - any-glob-to-any-file: 'packages/config/**/*'

"ci":
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
