# This file dictates which parts of the repo belong to which teams
# It is used by the "Labeler" GitHub Action to automatically tag PRs

"area: web":
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

"area: admin":
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

"area: droid":
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

"area: ui":
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

"area: core":
  - changed-files:
      - any-glob-to-any-file: 'packages/config/**/*'
      - any-glob-to-any-file: 'packages/database/**/*'
      - any-glob-to-any-file: 'packages/utils/**/*'
      - any-glob-to-any-file: 'packages/payment-engine/**/*'

"area: docs":
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

"area: ci":
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
